# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

env: &env
  TERM: dumb
  CI: "true"
  USER: circleci

jobs:
  build:
    docker:
    - image: cimg/openjdk:11.0.13
    environment:
      <<: *env
    steps:
      - checkout
      - run:
          name: build
          command: ./build.sh

  release:
    docker:
    - image: cimg/openjdk:11.0.13
    environment:
      <<: *env
    steps:
      - checkout
      - run:
          name: release
          command: |
            set -euo pipefail
            export PGP_PASSPHRASE=""
            export PGP_SECRET="$gpg_code_signing"
            export SONATYPE_PASSWORD="$MAVEN_PASSWORD"
            export SONATYPE_USERNAME="$MAVEN_USERNAME"
            export CI_COMMIT_TAG=1

            deploy=$(git log -n1 --format="%(trailers:key=deploy,valueonly)" $COMMIT)
            if [ "$deploy" = "true" ]; then
              while IFS='' read -r p || [ -n "$p" ]; do
                ./release.sh $p
              done < release.txt
            fi

workflows:
  version: 2
  build:
    jobs:
    - build
    - release:
        requires:
        - build
        context:
        # Despite the name, that's where the Sonatype credentials are.
        - npn-publish
        filters:
          branches:
            only: main
